version: "3"

services:
  middleware:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.middleware
    command: "pipenv run gunicorn main:app -b 0.0.0.0:5000"
    env_file:
      - env_file.env
    depends_on:
      - mongo-db

  web-server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.webserver
    env_file:
      - env_file.env
    ports:
      - '8080:8080'


  mongo-db:
    restart: always
    image: mongo:4.2.7
    env_file:
      - env_file.env

    volumes:
      - object_storage_mongo:/data/db

volumes:
  object_storage_mongo:
    external: true