FROM ubuntu:20.04

RUN apt update && apt install python3-pip python3-setuptools -y
RUN pip3 install -U pip
RUN pip3 install pipenv

RUN mkdir /app /app/src/
COPY ./src /app/src/
COPY Pipfile /app
COPY Pipfile.lock /app

WORKDIR /app
RUN pipenv install

WORKDIR /app/src
